# -*- coding: utf-8 -*-
"""Software Programs/Application Development -Text based ML tasks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19-LlxIjaT3mm7d6OqV_IbiQcg2c4Y7ia
"""

import boto3
import uuid

bot_name = 'StudentAdvisorBot'
bot_alias = 'TEST'
aws_region = 'your_aws_region'
user_id = str(uuid.uuid4())

try:

    lex_runtime = boto3.client('lex-runtime', region_name=aws_region)

    print(f"Connecting to Lex bot '{bot_name}' with alias '{bot_alias}' in region '{aws_region}'")
    print("-" * 20)

    while True:
        user_input = input("You: ")

        if user_input.lower() == 'quit':
            break

        response = lex_runtime.post_text(
            botName=bot_name,
            botAlias=bot_alias,
            userId=user_id,
            inputText=user_input
        )

        print(f"Bot: {response.get('message', 'No response from bot')}")

except Exception as e:
    print(f"An error occurred: {e}")